// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ9psPh08vrunF_8dswUH523JFEYRHJFE',
    appId: '1:245622335373:web:9e063190cfec94e6203fc4',
    messagingSenderId: '245622335373',
    projectId: 'green-mind-app',
    authDomain: 'green-mind-app.firebaseapp.com',
    storageBucket: 'green-mind-app.appspot.com',
    measurementId: 'G-3BWNW56WKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzTsvtB_s4YXcrfUlaJbPWVpYiQEGqDG0',
    appId: '1:245622335373:android:880b209f0b2cc19b203fc4',
    messagingSenderId: '245622335373',
    projectId: 'green-mind-app',
    storageBucket: 'green-mind-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_Jc29iVbylxDR9PkNfa4RlKVDLEMF10',
    appId: '1:245622335373:ios:3ada93c6bc24070b203fc4',
    messagingSenderId: '245622335373',
    projectId: 'green-mind-app',
    storageBucket: 'green-mind-app.appspot.com',
    iosBundleId: 'com.example.greenMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_Jc29iVbylxDR9PkNfa4RlKVDLEMF10',
    appId: '1:245622335373:ios:3ada93c6bc24070b203fc4',
    messagingSenderId: '245622335373',
    projectId: 'green-mind-app',
    storageBucket: 'green-mind-app.appspot.com',
    iosBundleId: 'com.example.greenMind',
  );
}
